#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03! (BCC32).
# Generated 14:36:58 28 Jan 2005
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
.AUTODEPEND

# Borland C++ tools
IMPLIB	= $(BCCROOT)\bin\Implib
ILINK32	= $(BCCROOT)\bin\ILink32
TLIB	= $(BCCROOT)\bin\TLib
BRC32	= $(BCCROOT)\bin\Brc32
TASM32	= $(BCROOT)\bin\Tasm32
CC  	= $(BCCROOT)\bin\BCC32

BCCROOT	= c:\borland\bcc55

HOMEV	=	
VPATH	=	$(HOMEV)\include
oDir	=	.
Bin	=	.
libDirs	=	-L$(BCCROOT)\lib;$(BCCROOT)\lib\psdk

incDirs	=	-I$(BCCROOT)\include

LD_FLAGS =	-v -Tpe -ap -c
C_FLAGS	=	-q -v\
	-D_WINVER=0x0400\
	-D_WIN32_WINNT=0x0400

SRCS	=\
	chisquare.cpp\
	component.cpp\
	componentmaintenance.cpp\
	edgefile.cpp\
	eelsmodel.cpp\
	eshift.cpp\
	fitter.cpp\
	fitterchooser.cpp\
	fitter_dialog.cpp\
	fixedpattern.cpp\
	gaussian.cpp\
	getfilename.cpp\
	getgraphptr.cpp\
	gettopspectrum.cpp\
	graph.cpp\
	hello.cpp\
	hsedge.cpp\
	image.cpp\
	imagedisplay.cpp\
	integerinput.cpp\
	interactive_parameter.cpp\
	kedge.cpp\
	kedgerel.cpp\
	ledge.cpp\
	line.cpp\
	logpoly.cpp\
	lorentz.cpp\
	lsqfitter.cpp\
	main.cpp\
	menu.cpp\
	mlfitter.cpp\
	model.cpp\
	monitor.cpp\
	monitorchooser.cpp\
	mscatter.cpp\
	multibyte.cpp\
	multispectrum.cpp\
	parameter.cpp\
	plasmon.cpp\
	powerlaw.cpp\
	realinput.cpp\
	saysomething.cpp\
	slice_iter.cpp\
	spectrum.cpp\
	spinsplitedge.cpp\
	tag.cpp\
	component.cpp~\
	spectrum.cpp~\
	curvematrix.cpp\
	expbackground.cpp\
	moc_componentmaintenance.cpp\
	moc_eelsmodel.cpp\
	moc_fileopener.cpp\
	moc_fitter_dialog.cpp\
	moc_fitterchooser.cpp\
	moc_getfilename.cpp\
	moc_graph.cpp\
	wlsqfitter.cpp\
	moc_getgraphptr.cpp\
	moc_hello.cpp\
	moc_image.cpp\
	moc_imagedisplay.cpp\
	moc_integerinput.cpp\
	moc_interactive_parameter.cpp\
	moc_menu.cpp\
	moc_monitorchooser.cpp\
	moc_realinput.cpp\
	moc_saysomething.cpp\
	model.cpp~\
	dos.cpp\
	dos.cpp~\
	logpoly.cpp~\
	main.cpp~\
	graph.cpp~\
	fileopener.cpp

EXOBJS	=\
	$(oDir)\chisquare.obj\
	$(oDir)\component.obj\
	$(oDir)\componentmaintenance.obj\
	$(oDir)\edgefile.obj\
	$(oDir)\eelsmodel.obj\
	$(oDir)\eshift.obj\
	$(oDir)\fitter.obj\
	$(oDir)\fitterchooser.obj\
	$(oDir)\fitter_dialog.obj\
	$(oDir)\fixedpattern.obj\
	$(oDir)\gaussian.obj\
	$(oDir)\getfilename.obj\
	$(oDir)\getgraphptr.obj\
	$(oDir)\gettopspectrum.obj\
	$(oDir)\graph.obj\
	$(oDir)\hello.obj\
	$(oDir)\hsedge.obj\
	$(oDir)\image.obj\
	$(oDir)\imagedisplay.obj\
	$(oDir)\integerinput.obj\
	$(oDir)\interactive_parameter.obj\
	$(oDir)\kedge.obj\
	$(oDir)\kedgerel.obj\
	$(oDir)\ledge.obj\
	$(oDir)\line.obj\
	$(oDir)\logpoly.obj\
	$(oDir)\lorentz.obj\
	$(oDir)\lsqfitter.obj\
	$(oDir)\main.obj\
	$(oDir)\menu.obj\
	$(oDir)\mlfitter.obj\
	$(oDir)\model.obj\
	$(oDir)\monitor.obj\
	$(oDir)\monitorchooser.obj\
	$(oDir)\mscatter.obj\
	$(oDir)\multibyte.obj\
	$(oDir)\multispectrum.obj\
	$(oDir)\parameter.obj\
	$(oDir)\plasmon.obj\
	$(oDir)\powerlaw.obj\
	$(oDir)\realinput.obj\
	$(oDir)\saysomething.obj\
	$(oDir)\slice_iter.obj\
	$(oDir)\spectrum.obj\
	$(oDir)\spinsplitedge.obj\
	$(oDir)\tag.obj\
	$(oDir)\component.obj\
	$(oDir)\spectrum.obj\
	$(oDir)\curvematrix.obj\
	$(oDir)\expbackground.obj\
	$(oDir)\moc_componentmaintenance.obj\
	$(oDir)\moc_eelsmodel.obj\
	$(oDir)\moc_fileopener.obj\
	$(oDir)\moc_fitter_dialog.obj\
	$(oDir)\moc_fitterchooser.obj\
	$(oDir)\moc_getfilename.obj\
	$(oDir)\moc_graph.obj\
	$(oDir)\wlsqfitter.obj\
	$(oDir)\moc_getgraphptr.obj\
	$(oDir)\moc_hello.obj\
	$(oDir)\moc_image.obj\
	$(oDir)\moc_imagedisplay.obj\
	$(oDir)\moc_integerinput.obj\
	$(oDir)\moc_interactive_parameter.obj\
	$(oDir)\moc_menu.obj\
	$(oDir)\moc_monitorchooser.obj\
	$(oDir)\moc_realinput.obj\
	$(oDir)\moc_saysomething.obj\
	$(oDir)\model.obj\
	$(oDir)\dos.obj\
	$(oDir)\dos.obj\
	$(oDir)\logpoly.obj\
	$(oDir)\main.obj\
	$(oDir)\graph.obj\
	$(oDir)\fileopener.obj

ALLOBJS	=	$(EXOBJS)
BCCJUNK	=	*.il* *.csm *.tds
ALLBIN	=	$(Bin)\eelsmodel.exe
ALLTGT	=	$(Bin)\eelsmodel.exe

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN) $(BCCJUNK)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------

# BCC32 DEF file: add after = if needed
BCC32DEF =
# BCC32 RT lib: cw32.lib static
BCC32RTLIB = cw32
# BCC32 Startup: c0x32.obj-console, c0w32.obj-winapi
BCC32STARTUP = c0x32.obj

#@# Dependency rules follow -----------------------------

$(Bin)\eelsmodel.exe : $(EXOBJS)
  $(ILINK32) @&&|
 $(LD_FLAGS) $(libDirs) +
$(BCC32STARTUP) +
$(oDir)\chisquare.obj +
$(oDir)\component.obj +
$(oDir)\componentmaintenance.obj +
$(oDir)\edgefile.obj +
$(oDir)\eelsmodel.obj +
$(oDir)\eshift.obj +
$(oDir)\fitter.obj +
$(oDir)\fitterchooser.obj +
$(oDir)\fitter_dialog.obj +
$(oDir)\fixedpattern.obj +
$(oDir)\gaussian.obj +
$(oDir)\getfilename.obj +
$(oDir)\getgraphptr.obj +
$(oDir)\gettopspectrum.obj +
$(oDir)\graph.obj +
$(oDir)\hello.obj +
$(oDir)\hsedge.obj +
$(oDir)\image.obj +
$(oDir)\imagedisplay.obj +
$(oDir)\integerinput.obj +
$(oDir)\interactive_parameter.obj +
$(oDir)\kedge.obj +
$(oDir)\kedgerel.obj +
$(oDir)\ledge.obj +
$(oDir)\line.obj +
$(oDir)\logpoly.obj +
$(oDir)\lorentz.obj +
$(oDir)\lsqfitter.obj +
$(oDir)\main.obj +
$(oDir)\menu.obj +
$(oDir)\mlfitter.obj +
$(oDir)\model.obj +
$(oDir)\monitor.obj +
$(oDir)\monitorchooser.obj +
$(oDir)\mscatter.obj +
$(oDir)\multibyte.obj +
$(oDir)\multispectrum.obj +
$(oDir)\parameter.obj +
$(oDir)\plasmon.obj +
$(oDir)\powerlaw.obj +
$(oDir)\realinput.obj +
$(oDir)\saysomething.obj +
$(oDir)\slice_iter.obj +
$(oDir)\spectrum.obj +
$(oDir)\spinsplitedge.obj +
$(oDir)\tag.obj +
$(oDir)\component.obj +
$(oDir)\spectrum.obj +
$(oDir)\curvematrix.obj +
$(oDir)\expbackground.obj +
$(oDir)\moc_componentmaintenance.obj +
$(oDir)\moc_eelsmodel.obj +
$(oDir)\moc_fileopener.obj +
$(oDir)\moc_fitter_dialog.obj +
$(oDir)\moc_fitterchooser.obj +
$(oDir)\moc_getfilename.obj +
$(oDir)\moc_graph.obj +
$(oDir)\wlsqfitter.obj +
$(oDir)\moc_getgraphptr.obj +
$(oDir)\moc_hello.obj +
$(oDir)\moc_image.obj +
$(oDir)\moc_imagedisplay.obj +
$(oDir)\moc_integerinput.obj +
$(oDir)\moc_interactive_parameter.obj +
$(oDir)\moc_menu.obj +
$(oDir)\moc_monitorchooser.obj +
$(oDir)\moc_realinput.obj +
$(oDir)\moc_saysomething.obj +
$(oDir)\model.obj +
$(oDir)\dos.obj +
$(oDir)\dos.obj +
$(oDir)\logpoly.obj +
$(oDir)\main.obj +
$(oDir)\graph.obj +
$(oDir)\fileopener.obj
$<,$*
import32.lib +
$(BCC32RTLIB).lib
$(BCC32DEF)


|
$(oDir)\chisquare.obj : chisquare.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ chisquare.cpp

$(oDir)\component.obj : component.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ component.cpp

$(oDir)\componentmaintenance.obj : componentmaintenance.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ componentmaintenance.cpp

$(oDir)\edgefile.obj : edgefile.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ edgefile.cpp

$(oDir)\eelsmodel.obj : eelsmodel.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ eelsmodel.cpp

$(oDir)\eshift.obj : eshift.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ eshift.cpp

$(oDir)\fitter.obj : fitter.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ fitter.cpp

$(oDir)\fitterchooser.obj : fitterchooser.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ fitterchooser.cpp

$(oDir)\fitter_dialog.obj : fitter_dialog.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ fitter_dialog.cpp

$(oDir)\fixedpattern.obj : fixedpattern.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ fixedpattern.cpp

$(oDir)\gaussian.obj : gaussian.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ gaussian.cpp

$(oDir)\getfilename.obj : getfilename.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ getfilename.cpp

$(oDir)\getgraphptr.obj : getgraphptr.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ getgraphptr.cpp

$(oDir)\gettopspectrum.obj : gettopspectrum.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ gettopspectrum.cpp

$(oDir)\graph.obj : graph.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ graph.cpp

$(oDir)\hello.obj : hello.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ hello.cpp

$(oDir)\hsedge.obj : hsedge.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ hsedge.cpp

$(oDir)\image.obj : image.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ image.cpp

$(oDir)\imagedisplay.obj : imagedisplay.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ imagedisplay.cpp

$(oDir)\integerinput.obj : integerinput.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ integerinput.cpp

$(oDir)\interactive_parameter.obj : interactive_parameter.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ interactive_parameter.cpp

$(oDir)\kedge.obj : kedge.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ kedge.cpp

$(oDir)\kedgerel.obj : kedgerel.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ kedgerel.cpp

$(oDir)\ledge.obj : ledge.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ ledge.cpp

$(oDir)\line.obj : line.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ line.cpp

$(oDir)\logpoly.obj : logpoly.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ logpoly.cpp

$(oDir)\lorentz.obj : lorentz.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ lorentz.cpp

$(oDir)\lsqfitter.obj : lsqfitter.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ lsqfitter.cpp

$(oDir)\main.obj : main.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ main.cpp

$(oDir)\menu.obj : menu.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ menu.cpp

$(oDir)\mlfitter.obj : mlfitter.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ mlfitter.cpp

$(oDir)\model.obj : model.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ model.cpp

$(oDir)\monitor.obj : monitor.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ monitor.cpp

$(oDir)\monitorchooser.obj : monitorchooser.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ monitorchooser.cpp

$(oDir)\mscatter.obj : mscatter.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ mscatter.cpp

$(oDir)\multibyte.obj : multibyte.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ multibyte.cpp

$(oDir)\multispectrum.obj : multispectrum.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ multispectrum.cpp

$(oDir)\parameter.obj : parameter.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ parameter.cpp

$(oDir)\plasmon.obj : plasmon.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ plasmon.cpp

$(oDir)\powerlaw.obj : powerlaw.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ powerlaw.cpp

$(oDir)\realinput.obj : realinput.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ realinput.cpp

$(oDir)\saysomething.obj : saysomething.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ saysomething.cpp

$(oDir)\slice_iter.obj : slice_iter.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ slice_iter.cpp

$(oDir)\spectrum.obj : spectrum.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ spectrum.cpp

$(oDir)\spinsplitedge.obj : spinsplitedge.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ spinsplitedge.cpp

$(oDir)\tag.obj : tag.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ tag.cpp

$(oDir)\component.obj : component.cpp~
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ component.cpp~

$(oDir)\spectrum.obj : spectrum.cpp~
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ spectrum.cpp~

$(oDir)\curvematrix.obj : curvematrix.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ curvematrix.cpp

$(oDir)\expbackground.obj : expbackground.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ expbackground.cpp

$(oDir)\moc_componentmaintenance.obj : moc_componentmaintenance.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_componentmaintenance.cpp

$(oDir)\moc_eelsmodel.obj : moc_eelsmodel.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_eelsmodel.cpp

$(oDir)\moc_fileopener.obj : moc_fileopener.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_fileopener.cpp

$(oDir)\moc_fitter_dialog.obj : moc_fitter_dialog.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_fitter_dialog.cpp

$(oDir)\moc_fitterchooser.obj : moc_fitterchooser.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_fitterchooser.cpp

$(oDir)\moc_getfilename.obj : moc_getfilename.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_getfilename.cpp

$(oDir)\moc_graph.obj : moc_graph.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_graph.cpp

$(oDir)\wlsqfitter.obj : wlsqfitter.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ wlsqfitter.cpp

$(oDir)\moc_getgraphptr.obj : moc_getgraphptr.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_getgraphptr.cpp

$(oDir)\moc_hello.obj : moc_hello.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_hello.cpp

$(oDir)\moc_image.obj : moc_image.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_image.cpp

$(oDir)\moc_imagedisplay.obj : moc_imagedisplay.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_imagedisplay.cpp

$(oDir)\moc_integerinput.obj : moc_integerinput.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_integerinput.cpp

$(oDir)\moc_interactive_parameter.obj : moc_interactive_parameter.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_interactive_parameter.cpp

$(oDir)\moc_menu.obj : moc_menu.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_menu.cpp

$(oDir)\moc_monitorchooser.obj : moc_monitorchooser.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_monitorchooser.cpp

$(oDir)\moc_realinput.obj : moc_realinput.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_realinput.cpp

$(oDir)\moc_saysomething.obj : moc_saysomething.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ moc_saysomething.cpp

$(oDir)\model.obj : model.cpp~
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ model.cpp~

$(oDir)\dos.obj : dos.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ dos.cpp

$(oDir)\dos.obj : dos.cpp~
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ dos.cpp~

$(oDir)\logpoly.obj : logpoly.cpp~
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ logpoly.cpp~

$(oDir)\main.obj : main.cpp~
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ main.cpp~

$(oDir)\graph.obj : graph.cpp~
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ graph.cpp~

$(oDir)\fileopener.obj : fileopener.cpp
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ fileopener.cpp

